# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-15 05:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('necessidade_esp', models.CharField(blank=True, max_length=120, null=True)),
                ('modalidade', models.CharField(choices=[('universal', 'Universal'), ('afro', 'Afrodescentende Carente'), ('pub', 'Escola Pública Carente'), ('def_ind', 'Portador de Deficiência / Indígena')], max_length=10)),
                ('reserva', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Inscrito'), (2, 'Deferido'), (3, 'Indeferido')], editable=False, null=True)),
                ('socio_economico', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Inscrito'), (2, 'Deferido'), (3, 'Indeferido')], editable=False, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('candidato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cidade_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidade_curso', to='cidades.Cidade')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.Curso')),
                ('local_prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_prova', to='cidades.Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='SocioEconomico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pai', models.CharField(max_length=120, null=True)),
                ('mae', models.CharField(max_length=120, null=True)),
                ('questao1', models.CharField(max_length=10, null=True)),
                ('questao2', models.CharField(max_length=10, null=True)),
                ('questao3', models.CharField(max_length=10, null=True)),
                ('questao4', models.CharField(max_length=10, null=True)),
                ('questao5', models.CharField(max_length=10, null=True)),
                ('questao6', models.CharField(max_length=10, null=True)),
                ('questao7', models.CharField(max_length=10, null=True)),
                ('questao8', models.CharField(max_length=10, null=True)),
                ('questao9', models.CharField(max_length=10, null=True)),
                ('questao10', models.CharField(max_length=10, null=True)),
                ('questao11', models.CharField(max_length=10, null=True)),
                ('questao12', models.CharField(max_length=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('inscricao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inscricoes.Inscricao')),
            ],
        ),
    ]
