# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 21:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0001_initial'),
        ('cidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('necessidade_esp', models.CharField(blank=True, max_length=120, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('candidato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cidade_curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cidade_curso', to='cidades.Cidade')),
                ('curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cursos.Curso')),
                ('local_prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_prova', to='cidades.Cidade')),
            ],
        ),
    ]
