# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='cidade_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidade_curso', to='cidades.Cidade'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.Curso'),
        ),
    ]
