# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0002_auto_20180411_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socioeconomico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questa1', models.CharField(max_length=10)),
                ('questa2', models.CharField(max_length=10)),
                ('questa3', models.CharField(max_length=10)),
                ('questa4', models.CharField(max_length=10)),
                ('questa5', models.CharField(max_length=10)),
                ('questa6', models.CharField(max_length=10)),
                ('questa7', models.CharField(max_length=10)),
                ('questa8', models.CharField(max_length=10)),
                ('questa9', models.CharField(max_length=10)),
                ('questa10', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('inscricao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inscricoes.Inscricao')),
            ],
        ),
    ]
