# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-15 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0002_recurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='reserva',
            field=models.CharField(blank=True, choices=[('1', 'Inscrito'), ('2', 'Deferido'), ('3', 'Indeferido')], editable=False, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='socio_economico',
            field=models.CharField(blank=True, choices=[('1', 'Inscrito'), ('2', 'Deferido'), ('3', 'Indeferido')], editable=False, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='status',
            field=models.CharField(choices=[('2', 'Deferido'), ('3', 'Indeferido')], max_length=120),
        ),
    ]
