# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0003_socioeconomico'),
    ]

    operations = [
        migrations.AddField(
            model_name='socioeconomico',
            name='mae',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='socioeconomico',
            name='pai',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='socioeconomico',
            name='questa11',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomico',
            name='questa1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomico',
            name='questa10',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomico',
            name='questa2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomico',
            name='questa3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomico',
            name='questa4',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomico',
            name='questa5',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomico',
            name='questa6',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomico',
            name='questa7',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomico',
            name='questa8',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='socioeconomico',
            name='questa9',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
