# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0003_auto_20180415_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='valor',
            field=models.CharField(default='100,00', max_length=6),
        ),
    ]
