# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0004_auto_20180414_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='socioeconomico',
            name='questa12',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
