# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0005_socioeconomico_questa12'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='modalidade',
            field=models.CharField(choices=[('universal', 'Universal'), ('afro', 'Afrodescentende Carente'), ('pub', 'Escola Pública Carente'), ('def_ind', 'Portador de Deficiência / Indígena')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricao',
            name='reserva',
            field=models.NullBooleanField(editable=False),
        ),
    ]
