# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0006_auto_20180414_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='socio_economico',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Inscrito'), (2, 'Deferido'), (3, 'Indeferido')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='reserva',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Inscrito'), (2, 'Deferido'), (3, 'Indeferido')], editable=False, null=True),
        ),
    ]
