# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0007_auto_20180414_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socioeconomico',
            old_name='questa1',
            new_name='questao1',
        ),
        migrations.RenameField(
            model_name='socioeconomico',
            old_name='questa10',
            new_name='questao10',
        ),
        migrations.RenameField(
            model_name='socioeconomico',
            old_name='questa11',
            new_name='questao11',
        ),
        migrations.RenameField(
            model_name='socioeconomico',
            old_name='questa12',
            new_name='questao12',
        ),
        migrations.RenameField(
            model_name='socioeconomico',
            old_name='questa2',
            new_name='questao2',
        ),
        migrations.RenameField(
            model_name='socioeconomico',
            old_name='questa3',
            new_name='questao3',
        ),
        migrations.RenameField(
            model_name='socioeconomico',
            old_name='questa4',
            new_name='questao4',
        ),
        migrations.RenameField(
            model_name='socioeconomico',
            old_name='questa5',
            new_name='questao5',
        ),
        migrations.RenameField(
            model_name='socioeconomico',
            old_name='questa6',
            new_name='questao6',
        ),
        migrations.RenameField(
            model_name='socioeconomico',
            old_name='questa7',
            new_name='questao7',
        ),
        migrations.RenameField(
            model_name='socioeconomico',
            old_name='questa8',
            new_name='questao8',
        ),
        migrations.RenameField(
            model_name='socioeconomico',
            old_name='questa9',
            new_name='questao9',
        ),
    ]
