# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enderecos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(max_length=120, unique=True)),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enderecos.Endereco')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
