# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-15 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=120)),
                ('curso', models.ManyToManyField(to='cursos.Curso')),
            ],
        ),
    ]
